version: '3'

services:
  api-gateway:
    build: .
    restart: always
    ports:
    - "80:80"
    - "443:443"
    volumes:
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    networks:
      - front-network
      - back-network
  
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    networks:
      - back-network

  golang_api:
    build: services/service01
    networks:
      - back-network

  deno_api:
    build: services/service02
    networks:
      - back-network

  python_api:
    build: services/service03
    networks: 
      - back-network

networks:
  back-network:
  front-network:
